version: '3'

services:
  strapi:
    container_name: strapi
    build: .
    volumes:
      - ./.env:/opt/app/.env
    ports:
      - "1337:1337"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - strapi
